use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :mylocal_cms, MylocalCmsWeb.Endpoint,
  load_from_system_env: true,
  url: [host: "grouchy-crowded-asianelephant.gigalixirapp.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :mylocal_cms, MylocalCmsWeb.Endpoint,
  server: true,
  secret_key_base: "${SECRET_KEY_BASE}"

config :mylocal_cms, MylocalCms.Repo,
        adapter: Ecto.Adapters.Postgres,
        url: System.get_env("DATABASE_URL"),
        pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
        ssl: true
